# Site settings
baseurl = "http://hbkapps.com/"
languageCode = "en-us"
title = "HBK Application Development Services"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-52362483-3"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "HBK Engineering Application Development Services"
	description = "HBK Engineering Application Development Services"

	# Navigation
	[params.navigation]
		brand = "HBK Apps"
		work = "Join Us"
		projects = "Our Projects"
		stack = "Our Stack"
		about = "About"
		team = "Team"
		contact = "Contact"

	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "We build apps that design"
		subtitle = "the internet"
		buttonText = "Tell me more"


	# Portfolio section
	[params.projects]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Our Projects"
		subtitle = "Here's what we've been working on lately:"

		[params.projects.modal]
            client = "Project"
            date = "Date"
            category = "Category"
          	buttonText = "Close Project"

	# Portfolio section
	[params.stack]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Our Stack"
		subtitle = "All of our applications are web-based. Here's a bit of what's going on behind the scenes:"

		[params.stack.modal]
            # client = "Website"
            # date = "Date"
            # category = "Category"
            # buttonText = "Close project"

		# Team section
		[params.team]
			title = "Our Team"
			subtitle = ""
			description = ""

			# All team member's pictures are stored under 'static/img/team'.
			# Replace them with your own too.
			[[params.team.members]]
				img = "1.jpg"
				name = "Mike Naughton"
				position = "Architect"
				description = "Mike is the fearless leader of the team. With almost a decade of software development experience, he has done a little bit of everything. Mike works closely with users of the application to make sure everything is running smoothly. In his free time, Mike likes to pursue his hobbies of aviation, sailing, and volunteering."
				social = [
					# ["fa-twitter", "#"],
					# ["fa-facebook", "#"],
					# ["fa-linkedin", "#"]
				]

			[[params.team.members]]
				img = "2.jpg"
				name = "Matt Glynn"
				position = "Full Stack Developer"
				description = "Matt is our \"go-to guy\" for squashing bugs and making sure that our applications are working just right. He comes to HBK with a background in electrical engineering and experience working on several different software teams. When he's not wrangling JavaScript, Matt likes to spend time experimenting with electronics, practicing Brazilian Jiu-Jitsu, and working on startups."
				social = [
					# ["fa-twitter", "#"],
					# ["fa-facebook", "#"],
					# ["fa-linkedin", "#"]
				]

			[[params.team.members]]
				img = "3.jpg"
				name = "Brett Neese"
				position = "Swiss Army Knife"
				description = ""
				social = [
					# ["fa-twitter", "#"],
					# ["fa-facebook", "#"],
					# ["fa-linkedin", "#"]
				]

		# work section
		[params.work]
			title = "Join us!"
			subtitle = "Sound like fun? We'd love to have you join our team."
			buttonText = "Apply Now!"

					[[params.work.row]]
							[[params.work.row.list]]
									icon = "fa-clock-o"
									title = "Flexible Hours"
									description = "At HBK, we understand the value of a work-life balance. We also understand that some people do their best work early in the morning while others are rockstars at night. We care more about what you do than when you do it."

							[[params.work.row.list]]
									icon = "fa-laptop"
									title = "Latest Tech"
									description = "Our team is always experimenting with the latest web development technologies and practices. From forays into ES6 to managing deployments with Red Hat®'s OpenShift, we're constantly looking for technologies that help us improve our products."

							[[params.work.row.list]]
									icon = "fa-coffee"
									title = "Entrepreneurial Team"
									description = "The Application Development team at HBK is small, agile, and open to new ideas. Whether you're an intern or a full-time employee, you can be sure that your contributions will have an impact for our team and for our users."


	# Footer section
	[params.footer]
		copyright = "©2016 HBK Engineering, LLC"
