# Site settings
baseurl = "http://hbkengineering.github.io/landing-page/"
languageCode = "en-us"
title = "HBK Application Development Services"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-52362483-3"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "HBK Engineering Application Development Services"
	description = "HBK Engineering Application Development Services"

	# Navigation
	[params.navigation]
		brand = "HBK Apps"
		work = "Work for Us"
		portfolio = "Our Projects"
		about = "About"
		team = "Team"
		contact = "Contact"

	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "We build apps that build"
		subtitle = "the internet"
		buttonText = "Tell me more"
	# work section
	[params.work]
		title = "Work for Us!"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		buttonText = "Apply Now!"

        [[params.work.row]]
            [[params.work.row.list]]
                icon = "fa-clock-o"
                title = "Flexible hours"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

            [[params.work.row.list]]
                icon = "fa-laptop"
                title = "Latest Tech"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

            [[params.work.row.list]]
                icon = "fa-lock"
                title = "Close-knit team"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

	# Portfolio section
	[params.portfolio]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Our Projects"
		subtitle = "We <3 open source. Here are some open source projects we've been hacking on:"

		[params.portfolio.modal]
            client = "Project"
            date = "Date"
            category = "Category"
            buttonText = "Close project"

  # About section
	[params.about]
		title = "About"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		text = "Lorem ipsum dolor sit amet consectetur."

	# Footer section
	[params.footer]
		copyright = "©2016 HBK Engineering, LLC"
